//Expressions Watch Window Variables for Lab 1 (Open Loop VMC)
expRemoveAll()
//Variables
expAdd ("boost_pwm",getNatural())
expAdd ("inv_pwm",getNatural())
expAdd ("pwm7_duty",getNatural())
expAdd ("pwm8_duty",getNatural())
expAdd ("pwm1_duty",getNatural())
expAdd ("pwm3_duty",getNatural())
expAdd ("Vin",getNatural())
expAdd ("Vout",getNatural())
expAdd ("Ia",getNatural())
expAdd ("Ib", getNatural())
expAdd ("Ic",getNatural())
expAdd ("IL",getNatural())
expAdd ("throttle",getNatural())